# Generated by Django 2.2.10 on 2020-02-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app_host',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceregistry',
            name='external_uri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceregistry',
            name='service_route',
            field=models.CharField(max_length=255),
        ),
    ]
