# Generated by Django 2.0 on 2018-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20181004_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
