# Generated by Django 2.0 on 2018-10-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_application_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='active_status',
            new_name='is_active',
        ),
    ]
