# Generated by Django 2.0 on 2018-10-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_auto_20181005_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='service_path',
            new_name='app_host',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='service_port',
            new_name='app_port',
        ),
    ]
