# Generated by Django 2.0 on 2018-10-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_auto_20181005_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistry',
            name='callback_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.ServiceRegistry'),
        ),
    ]
