# Generated by Django 2.0 on 2018-10-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_auto_20181005_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.ServiceRegistry'),
        ),
    ]
