# Generated by Django 2.0 on 2018-10-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_auto_20181005_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='async_result_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='request_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
