# Generated by Django 2.0.8 on 2018-11-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0012_serviceregistrytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistry',
            name='post_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', related_query_name='poster', to='gateway.ServiceRegistry'),
        ),
    ]
