# Generated by Django 2.0.8 on 2018-11-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0013_serviceregistry_post_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceregistrytask',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceRegistryTask',
        ),
    ]
