# Generated by Django 2.0.8 on 2018-12-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0014_auto_20181116_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='async_result_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
