# Generated by Django 2.0.8 on 2018-12-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0015_auto_20181214_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistry',
            name='has_active_task',
            field=models.BooleanField(default=False),
        ),
    ]
