# Generated by Django 2.0.8 on 2018-12-20 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0017_requestlog_task_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='task_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_log', to='django_celery_results.TaskResult'),
        ),
    ]
