# Generated by Django 2.0.8 on 2019-01-16 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gateway', '0018_auto_20181220_0428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consumer',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='serviceregistry',
            old_name='consumers',
            new_name='sources',
        ),
    ]
