# Generated by Django 2.0.13 on 2019-10-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0021_requestlog_task_result_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='health_check_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
