# Generated by Django 2.2.10 on 2020-03-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_remove_serviceregistry_post_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceregistry',
            options={'ordering': ['application__name', 'name']},
        ),
    ]
