# Generated by Django 2.2.10 on 2020-04-23 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20200323_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistry',
            name='callback_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.ServiceRegistry'),
        ),
    ]
